// SPDX-License-Identifier: GPL-3.0-or-later
package dev.lyo.callrec.storage

import android.content.Context
import dev.lyo.callrec.settings.AppSettings
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Names and creates on-disk targets for raw PCM dumps. Returns a
 * [RecordingFile] which the encoder layer turns into a properly-formatted
 * WAV (or, in v1.0, Ogg/Opus) file.
 *
 * Naming convention:
 *   <yyyy-MM-dd_HH-mm-ss>__<callId>__<tag>.wav
 *
 * `callId` is a short ULID-ish stamp generated by the caller — it groups the
 * uplink/downlink halves of one call together in the library list.
 */
class RecordingStorage(
    private val appCtx: Context,
    @Suppress("unused") private val settings: AppSettings,
) {
    private val baseDir: File by lazy {
        // External files dir is per-app, mounted on shared storage. Indexed
        // by MediaStore (so users can find the WAVs in any file picker) but
        // wiped on uninstall. v1.0 will let users pin a SAF tree URI and
        // mirror the writes there.
        appCtx.getExternalFilesDir(null)?.resolve("recordings")?.apply { mkdirs() }
            ?: appCtx.filesDir.resolve("recordings").apply { mkdirs() }
    }

    fun newCallId(): String {
        // 5-char base32 of the millisecond timestamp — short, sortable, and
        // unique within the same call (two parallel files share it).
        val v = System.currentTimeMillis()
        val sb = StringBuilder(8)
        var r = v
        repeat(5) { sb.append(BASE32[(r and 0x1F).toInt()]); r = r ushr 5 }
        return sb.reverse().toString()
    }

    fun create(callId: String, tag: String, ext: String): RecordingFile {
        val ts = TIMESTAMP.format(Date())
        val name = "${ts}__${callId}__${tag}"
        val file = File(baseDir, "$name.$ext")
        return RecordingFile(name = name, tag = tag, path = file.absolutePath)
    }

    fun listAll(): List<File> =
        baseDir.listFiles()?.sortedByDescending { it.lastModified() } ?: emptyList()

    companion object {
        // Canonical Crockford base32: 32 unique chars, digits before letters,
        // I/L/O/U omitted. The earlier "ABCDEFGHJKMNPQRSTVWXYZ23456789X"
        // had only 30 unique chars + a duplicate 'X' to pad to 31 — and was
        // indexed with `0x1F` (0..31), so the mask could fall off the end.
        private const val BASE32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
        private val TIMESTAMP = SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.US)
    }
}
